language: java
jdk:
- oraclejdk8
before_install:
- unset _JAVA_OPTIONS
install:
- "./mvnw --version"
script:
- sudo ./mvnw install
cache:
  directories:
  - "$HOME/.m2/"
after_success:
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X}
  != X ]; then ./mvnw deploy -DskipTests=true --settings travis-settings.xml; fi
env:
  secure: KRPCfUWX3dHgD4ZT+TF9cma43EV0LjRk7YbLYPTdQ5EXIvNp5dYzQO1a2rPPecHz1WOJxt5vm0WSInIARDRkwZl+cxKrT/ZSuz6YRu1Ud/LgV3yRKm+WcqX8kUhnDnCdPkh0/r6VHnJrqxs6hoJ2krle+xUoW5zh8rVnqyqz/3u56r2uUjABHOiGvMSNNUeRkdbyBWW3V3RW0F05XPGDAYVANNUJrrVtXeBoz+3cwFQpXuMfwoaPNSzfQBEv25xiTaoX59tWeq0iceqBlyYb54EBuMOsUiT9cMLleB64MH5cwiTgkXzrNtDAQAio5FgvD/L9wkzdoxR3NC21pl0QP4K6qh8vA9dcILfD3G0JfQNdmP9fWZbAqJQtgzRslhCJRmddd0hgfqtM94RQh75dvVUYzv/ZIFJy2U96D5ZlOU7cOUDIB9ZX0vJ5Ze8tBckC0is26g2cacp36Zr7772K3x+OmC+QRBf9pqQYqgH+lWkfw0qDp61xyPf9ZEXv4xlWbD3bLAHmBHD2WWUza7JbUwicRnhEjBrrw6AZmtiONEf81INtCmlPkmFIzADHQuN60SVM4tNIvczk1Ihp/xouyeZiacxBxDBTieSFyiBwQ9cWFZ3KSF9c9ztPhgruIodyAQQM7uCGGbkFpIYHMVh8PzMsrAyYoUuII6XoipmDLIo=
  secure: KnmkYgkxQ8j5vwuJnIt96ov/RCq6KSG9Ph/oPsc+4Y7YXmvBonbyOCGUg5HchD7GjgPyP0cfUsKu8o5NzrZcMas3FRwZkGMYHvblV3aMBfXnUegPpRN7QjMhq8f4iwKGEjCoFc8kn0DfePSwZlTcOhmC/+OQCYSvlXp29ome54grpiqRwCJD4kaqC8mcIoWym34UwZVKhGHte/b/8ldlsg9s9B4zcu4aQq9Jl0+xdL4PUVyKgRnhZpb0pWYzezZ1ECvMPz7u80Rky3D9l/MAipMUi91Qrpz4vwBircxWejT/iS3H3n3aIyTP+e3ug47r0fEuLHTZbM4DvBbFxHA3xpbf+BGZ1GlUe9NnJbcIQ8Y+l4zS/k8Htk7xc0nUlUOs06hshRWiNwCSju1YzklwhpuYV07wZTPiUpd7sgMLnPD6S7RGUpojX2R73Cr5O17nTo0rtEFmhhEklASwQ4DIcqABsqrt7NTf2vGBCBThW0r0b7H1pzIKxaDATZzqR/2pxgdbkpjz5FUFjsJLqiaWepzHjZdkCOcSQtKkapHUPZHkZc8hiP2suD3QB3T0NY5/Ci7SpQlxpAdScGP+HUcuTQCpj65ACrS0pH3LPNxyESnfLjBmQg9WPVR5W59iGwwaG01BWwrznRhsLh5oA+ayYH1QRhf3euEOL6hM0kJ5Yio=
