language: java
jdk:
- oraclejdk8
before_install:
- unset _JAVA_OPTIONS
install:
- "./mvnw --version"
script:
- sudo ./mvnw install
cache:
  directories:
  - "$HOME/.m2/"
after_success:
- echo $REPOSITORY_USERNAME
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_BRANCH
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${REPOSITORY_USERNAME:=X}
  != X ]; then ./mvnw deploy -DskipTests=true --settings travis-settings.xml; fi
env:
  global:
  - secure: KUbJJWaH2P3/rVr10jKx1dDCY+9sOLyucLPbkY/XYgnUcvACY9+g8IMJcLGE20re381cyUXthv5BIJVexLhknWCI75bZRtAbeZopCjfnGaS4pxXOVot3I2rrMgOUm88NDG3LoVEkXVKSaO+qKGNShDAiDpfGz4hl2Rrk490dAsRVN8LgNhboFKNoPO8NQ47+Wdjt3dFbAen0YMpP0w678MGLGhYSmwpgsspUcnDZ/mq/9q9Plr1bV46bF8sJ9Cgc6aYQI/RZIeETXgbvm8uY3IxYHAvYbzEk9s4N74B309k841KK0AGA0C3mtQOnXgI/UqFqXZxYX08l7dGbOs+Jd9Gf82dYlSSukxQJ1wnoKK35nmucGR2lz3C5G2wUbM/0PDTwnRrbIanNCK6/Y/kA1r7J7WbMLj9oTgdtIQwhbTa8gx0pCIkjlCPhWg//g6XddDOTRrp53wqXgPHGwtBuYjFUAtlWkm7PZh9ylAgAL+6UCD6QfComY3hg5++Bvcf/YTq7RNzmkPMTUpMSJI0fqvp2+zuA7eiPRAyyLqkbnPMv0Z8rVBTyn4ToA8odJFTwJ8mTjZ8p57VYUFzf7p58T7B5QeMIIiuGbaKf+jACFrvhgoGsVBzI7a4odVa5U1ukoCkLGJfuCDs0hPOdO6i/I2ezR3HGDkHo6ExswSBrbTk=
  - secure: gCx5hRINpfaEw3GCGkLcP/g1jpiYnD5SOFYpkCC0HPVN5x+LhUlfs4iN0gjd+wGvKmZhbY0xCUhT/uEVKBUxtGdGRsYezXA6R6aB1UWQa842UgvUJr1j3EnorTZOBhFHtu0kG3+1s/FAlXhnsbOdccUAaf6HjDAsgqzCA+LM6Jcred1LyEfG30MnMnr6Em5RADQkLhduWMSt5TiXW0ijyGf9Ep7G+n6SBbqWghRuSNyM2C/i5X1IJvkYOKW2OgXphcVT+TSYYPbujQg8KhIphJLxLv9MoMLIA0Xy/NY78TmtwOkTc5bUrRiohnvRQnnmBcLU9y8skLdZdky48j8PtGSQIM++lO219X2mpxLywpkn9f91b5h40FsX4io1rSrh7fhkcNEJn70ULhAKcFK7Olh7eGPdqdfWmtgdSG8P3ZSB9aUQZZTnQ0FfepnVXbw2VlqjR9X7Gsx8fVJ84zo3a5roIKDX7lgSuEHC2ZU0VBxHMtNjcUzu/Vg/lzYtiRWqyP3nzb8FP25oZT5sRRjQrw38T6af3838TQ6Y4jba/k9+fs30NCL+1pg2IzQvIpzLBkxWVKQIpABMJPW84dB5So+MzcOgQx4BJ4R2ZG/C3PHYr7IgduSlTRljee1ISBMlVowFRgep/HdAYgj595HUqzolTL2Hz3EaPMmuhIOfb3w=
